services:
  db:
    image: postgres:15-alpine
    container_name: libreria_db
    restart: always
    environment:
      POSTGRES_USER: usuario_local
      POSTGRES_PASSWORD: password_seguro
      POSTGRES_DB: libreria_backend_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      retries: 10

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: libreria_api
    restart: always
    ports:
      - "3000:3000"
      - "5555:5555"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/src:/app/src
      - ./backend/prisma:/app/prisma
      - ./backend/prisma.config.ts:/app/prisma.config.ts
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=usuario_local
      - DB_PASSWORD=password_seguro
      - DB_NAME=libreria_backend_db
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data: